### PR TITLE
Restore backward-compatibility for reading FITS and HDF5 files

### PR DESCRIPTION
**Pull request by astrofrog**
This fixes issues with loading old files after #142 

Also added very basic unit tests

### CODE REVIEW

**Comment by astrofrog** [comment]
@e-koch - note that in the last commit, I made a small change to your additions, which is to store the settings in attributes rather than datasets (attributes are more appropriate in this case). So this will break compatibility with any files that you created since your latest commit (but this was never in a stable version so we don't need to fix that)

**Comment by astrofrog** [comment]
cc @ChrisBeaumont @keflavich

**Comment by e-koch** [comment]
@astrofrog - Thanks for the heads up!

**Comment by keflavich** [comment]
:+1:

**Comment by ChrisBeaumont** [comment]
+1

**Pull request merged**
