### PR TITLE
h5py removed .value after v3

### PR DESCRIPTION
**Pull request by indebetouw**
in v3, value was removed from Structure.  
these changes instead return strings for newick and wcs_header, and numpy arrays for data and index_map, when reading a saved hdf5 dendrogram.

### CODE REVIEW

**Comment by keflavich** [comment]
lgtm, but I don't know enough about hdf5 to review this usefully.  Anyone else want to chime in?

(we really need tests / CI)

**Comment by indebetouw** [comment]
I don't know what level of compatibility you want to maintain with older versions of h5py, or even with Python2. 
I did test with both h5py v>3 and v<3, but I did not test with Python2. In particular the conversion of byte to string was unnecessary back in python2.

**Comment by keflavich** [comment]
We don't need to maintain any support of python 2.  I'm not sure about h5py though.

**Comment by e-koch** [comment]
Might impact loading dendrograms with glue: https://github.com/glue-viz/glue/blob/ed71979f8e0e41f993a2363b3b5a8f8c3167a130/glue/plugins/dendro_viewer/data_factory.py#L81

@astrofrog?

**Comment by astrofrog** [comment]
I'll investigate!

**Review by astrofrog — APPROVED** [review]
This seems to be needed so I will merge and look later into what we need to do on the glue side

**Pull request merged**
